---
- hosts: all
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "/home/enzuru/Downloads/game-server.pem"

  tasks:
  - name: pull
    shell: docker pull 599503031631.dkr.ecr.us-west-1.amazonaws.com/zelpy-server

  - name: stop
    shell: docker stop $(docker ps -aq)

  - name: start
    shell: docker run -p 5005:5005/udp 599503031631.dkr.ecr.us-west-1.amazonaws.com/zelpy-server > zelpy-server.log
    async: 45
    poll: 0
