---
- hosts: all
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "/home/enzuru/Downloads/game-server.pem"

  tasks:
  - name: restart
    shell: docker restart $(docker ps -aq)
    async: 45
    poll: 0
